### ISSUE TITLE
Graph has not attribute 'node'

### ISSUE THREAD

**Issue by AK-1000** [ymirsky/CIoTA-Sim#1]
Running DES to simulate 1000 agents over 10 blocks:
L: 800
T: 60 seconds
Agent Connectivity: smallworld
Traceback (most recent call last):
  File "C:\CIoTA-Sim\CIoTA-Sim-master\example.py", line 15, in <module>
    G, num_blocks, epochs_per_block = simulator.run(num_blocks=10, print_progress=True)
  File "C:\CIoTA-Sim\CIoTA-Sim-master\DiscreetEventSimulator.py", line 213, in run
    agent.broadcast() #send chain+pb to all neighbors
  File "C:\CIoTA-Sim\CIoTA-Sim-master\DiscreetEventSimulator.py", line 52, in broadcast
    G.node[nnode]['agent'].receive_chain(self.chain,self.pb)
AttributeError: 'Graph' object has no attribute 'node'

**Comment by evalexp** [comment]
Do you sovle it? I have the same problem.

**Comment by evalexp** [comment]
same problem as you, just edit the code on line 52, replace:
```python
G.node[nnode]['agent'].receive_chain（self.chain，self.pb）
```
with:
```python
G.nodes[nnode]['agent'].receive_chain（self.chain，self.pb）
```
It's `G.nodes`, not `G.node`
